[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[project]
name = "gridfinityworkbench"
version = "0.7.1"

[project.optional-dependencies]
dev = ["ruff", "freecad-stubs"]
