name: Tests
on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: ruudjhuu/freecad:v0.0.1
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests
        run: python -m unittest discover tests -v
